import 'package:get/get_navigation/src/root/internacionalization.dart';

class LocalString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "en": {
          "Welcome Back!": "Welcome Back!",
          "Please login to continue.": "Please login to continue.",
          "User ID *": "User ID *",
          "User Password *": "User Password *",
          "Remember me": "Remember me",
          "Log In": "Log In",
          "Don’t have an account?": "Don’t have an account?",
          " Sign Up": " Sign Up",
          "English": "English",
          "Forgot Password?": "Forgot Password?",
          "Enter the email associated with your account and\nwe’ll send an email with instructions to reset\nyour password.":
              "Enter the email associated with your account and\nwe’ll send an email with instructions to reset\nyour password.",
          "Send": "Send",
          "Email ID *": "Email ID *",
          "Enter 4 Digits Code": "Enter 4 Digits Code",
          "Enter the 4 digits code that you received on your\nemail.":
              "Enter the 4 digits code that you received on your\nemail.",
          "Continue": "Continue",
          "Confirm": "Confirm",
          "Not Received?": "Not Received?",
          " Resend": " Resend",
          " Reset Password": " Reset Password",
          "At least 8 characters in length.":
              "At least 8 characters in length.",
          "It’s better to have.": "It’s better to have.",
          "Upper & lower Case letter’s.": "Upper & lower Case letter’s.",
          "A Symbol (#\$%).": "A Symbol (#\$%).",
          "A longer password.": "A longer password.",
          "New Password": "New Password",
          "Re-enter New Password": "Re-enter New Password",
          "Logout from All": "Logout from All",
          "Save Device": "Save Device",
          "Yaah!!\nSuccessful": "Yaah!!\nSuccessful",
          "Password is Successfully Update !!!\nKeep Login With new password":
              "Password is Successfully Update !!!\nKeep Login With new password",
          "Done!!\nSuccessful": "Done!!\nSuccessful",
          "My Profile": "My Profile",
          "First Name": "First Name",
          "Name": "Name",
          "Username": "Username",
          "Contact Number": "Contact Number",
          "Address": "Address",
          "Postcode": "Postcode",
          "City": "City",
          "Join Date": "Join Date",
          "Employee Nr.": "Employee Nr.",
          "Vacation Days": "Vacation Days",
          "Working hours a week": "Working hours a week",
          "Update": "Update",
          "Today Work Details": "Today Work Details",
          "Work Address": "Work Address",
          "Enter Work Address": "Enter Work Address",
          "Hours": "Hours",
          "Minutes": "Minutes",
          "Enter Hours": "Enter Hours",
          "Enter Minutes": "Enter Minutes",
          "Contact Person": "Contact Person",
          "Enter Contact Person": "Enter Contact Person",
          "Enter Contact Number": "Enter Contact Number",
          "Starttime": "Starttime",
          "Enddtime": "Enddtime",
          "My Task for Today": "My Task for Today",
          "Clean the Floor": "Clean the Floor",
          "Clean the windows": "Clean the windows",
          "Dry Clean Sheets": "Dry Clean Sheets",
          "Clean Desk": "Clean Desk",
          "Paper work": "Paper work",
          "Lunch Break": "Lunch Break",
          "Cleaning Entrance": "Cleaning Entrance",
          "Watering All Plants": "Watering All Plants",
          "Clean All Windows": "Clean All Windows",
          "Arrange All Files": "Arrange All Files",
          "Lights off All Rooms": "Lights off All Rooms",
          "Request for Signature": "Request for Signature",
          " (Optional)": " (Optional)",
          "If your task is done then for the confirmation please kindly\ntake the signature from the Admin.":
              "If your task is done then for the confirmation please kindly\ntake the signature from the Admin.",
          "Main Task List": "Main Task List",
          "Download": "Download",
          "Could not clean the window, because no windows":
              "Could not clean the window, because no windows",
          "Successfully added To Work !\nKindly Login Next Day for your Workship":
              "Successfully added To Work !\nKindly Login Next Day for your Workship",
          "Add Signature": "Add Signature",
          "Restaurant Athens": "Restaurant Athens",
          "Deine Einsätze": "Deine Einsätze",
          "3 Objects today": "3 Objects today",
          "January": "January",
          "February": "February",
          "March": "March",
          "April": "April",
          "May": "May",
          "June": "June",
          "July": "July",
          "August": "August",
          "September": "September",
          "October": "October",
          "November": "November",
          "December": "December",
          "Choose additional Object for the day":
              "Choose additional Object for the day",
          "Search for Object": "Search for Object",
          "Search here": "Search here",
          "Timerecording": "Timerecording",
          "Today Work Details": "Today Work Details",
          "My Task for Today": "My Task for Today",
          "Could not clean the window, because no windows":
              "Could not clean the window, because no windows",
          "Save": "Save",
          "Create Signature": "Create Signature",
          "Please do your signature": "Please do your signature",
          "Camera": "Camera",
          "Gallery": "Gallery",
          "Edit": "Edit",
          "Add Problem": "Add Problem",
          "Submit": "Submit",
        },
        "gr": {
          "Welcome Back!": "Willkommen zurück!",
          "Please login to continue.": "Bitte einloggen zum Fortfahren.",
          "User ID *": "Benutzer-ID *",
          "User Password *": "Benutzer-Passwort *",
          "Remember me": "Mich erinnern",
          "Log In": "Anmeldung",
          "Don’t have an account?": "Sie haben kein Konto?",
          " Sign Up": " Anmeldung",
          "German": "Deutsch",
          "English": "Englisch",
          "Forgot Password?": "Passwort vergessen?",
          "Enter the email associated with your account and\nwe’ll send an email with instructions to reset\nyour password.":
              "Geben Sie die E-Mail-Adresse ein, die Ihrem Konto zugeordnet ist, und\nwir senden Ihnen eine E-Mail mit Anweisungen zum Zurücksetzen\nIhres Passworts.",
          "Send": "Schicken",
          "Email ID *": "E-Mail-ID *",
          "Enter 4 Digits Code": "Geben Sie den 4-stelligen Code ein",
          "Enter the 4 digits code that you received on your\nemail.":
              "Geben Sie den 4-stelligen Code ein, den Sie per E-Mail erhalten haben.",
          "Continue": "Weitermachen",
          "Confirm": "Bestätigen",
          "Not Received?": "Nicht erhalten?",
          " Resend": " Erneut senden",
          " Reset Password": " Passwort zurücksetzen",
          "At least 8 characters in length.": "Mindestens 8 Zeichen lang.",
          "It’s better to have.": "Es ist besser zu haben.",
          "Upper & lower Case letter’s.":
              "Obere Kleinbuchstaben: das obere Kleingedruckte.",
          "A Symbol (#\$%).": "Ein Symbol (#\$%).",
          "A longer password.": "Ein längeres Passwort.",
          "New Password": "Neues Kennwort",
          "Re-enter New Password": "Neues Passwort erneut eingeben",
          "Logout from All": "Von Alle abmelden",
          "Save Device": "Gerät speichern",
          "Yaah!!\nSuccessful": "Yaah!!\nErfolgreich",
          "Password is Successfully Update !!!\nKeep Login With new password":
              "Passwort wurde erfolgreich aktualisiert !!!\nMit neuem Passwort anmelden",
          "Done!!\nSuccessful": "Fertig!!\nErfolgreich",
          "My Profile": "Mein Profil",
          "First Name": "Vorname",
          "Name": "Name",
          "Username": "Nutzername",
          "Contact Number": "Kontakt Nummer",
          "Address": "Adresse",
          "Postcode": "Postleitzahl",
          "City": "Stadt",
          "Join Date": "Beitrittsdatum",
          "Employee Nr.": "Mitarbeiter Nr.",
          "Vacation Days": "Ferientage",
          "Working hours a week": "Arbeitsstunden pro Woche",
          "Update": "Aktualisieren",
          "Today Work Details": "Heute Arbeitsdetails",
          "Work Address": "Arbeitsadresse",
          "Enter Work Address": "Arbeitsadresse eingeben",
          "Hours": "Std",
          "Minutes": "Protokoll",
          "Enter Hours": "Geben Sie Stunden ein",
          "Enter Minutes": "Minuten eingeben",
          "Contact Person": "Gesprächspartner",
          "Enter Contact Person": "Ansprechpartner eingeben",
          "Enter Contact Number": "Kontaktnummer eingeben",
          "Starttime": "Startzeit",
          "Enddtime": "Endzeit",
          "My Task for Today": "Meine Aufgabe für heute",
          "Clean the Floor": "Reinigen Sie den Boden",
          "Clean the windows": "Die Fenster putzen",
          "Dry Clean Sheets": "Trockenreinigungstücher",
          "Clean Desk": "Sauberer Schreibtisch",
          "Paper work": "Papierkram",
          "Lunch Break": "Mittagspause",
          "Cleaning Entrance": "Eingang reinigen",
          "Watering All Plants": "Alle Pflanzen gießen",
          "Clean All Windows": "Alle Fenster reinigen",
          "Arrange All Files": "Alle Dateien anordnen",
          "Lights off All Rooms": "Licht aus allen Räumen",
          "Add Signature": "Signatur hinzufügen",
          " (Optional)": " (Optional)",
          "If your task is done then for the confirmation please kindly\ntake the signature from the Admin.":
              "Wenn Ihre Aufgabe erledigt ist, nehmen Sie bitte zur Bestätigung die Unterschrift vom Admin entgegen.",
          "Main Task List": "Hauptaufgabenliste",
          "Download": "Herunterladen",
          "Could not clean the window, because no windows":
              "Konnte das Fenster nicht putzen, weil keine Fenster",
          "Successfully added To Work !\nKindly Login Next Day for your Workship":
              "Erfolgreich zur Arbeit hinzugefügt!\nBitte melden Sie sich am nächsten Tag für Ihr Arbeitsverhältnis an",
          "Restaurant Athens": "Restaurant Athen",
          "Deine Einsätze": "Deine Einsätze",
          "3 Objects today": "3 Objekte heute",
          "January": "January",
          "February": "February",
          "March": "March",
          "April": "April",
          "May": "May",
          "June": "June",
          "July": "July",
          "August": "August",
          "September": "September",
          "October": "October",
          "November": "November",
          "December": "December",
          "Choose additional Object for the day":
              "Wählen Sie ein zusätzliches Objekt für den Tag",
          "Search for Object": "Suche nach Objekt",
          "Search here": "Suche hier",
          "Timerecording": "Zeiterfassung",
          "Today Work Details": "Heute Arbeitsdetails",
          "My Task for Today": "Meine Aufgabe für heute",
          "Could not clean the window, because no windows":
              "Konnte das Fenster nicht putzen, weil keine Fenster",
          "Save": "Speichern",
          "Create Signature": "Signatur erstellen",
          "Please do your signature": "Bitte unterschreiben Sie",
          "Camera": "Kamera",
          "Gallery": "Galerie",
          "Request for Signature": "Request for Signature",
          "Edit": "Edit",
          "Add Problem": "Add Problem",
          "Submit": "Submit",
        }
      };
}
